Add demo website
teobais/percircle-vue pull request #8
Opened 2022-01-30 03:11 UTC by richardsaseun14

2022-01-30 03:13 UTC, richardsaseun14 commented
@teobais @miller-kevin I will be using this pull request to continue building the website if that is fine.

I am currently redoing the previous work I did before

2022-01-30 03:57 UTC, richardsaseun14 commented
I have made some more changes and they are available on https://richardsaseun14.github.io/percircle-vue/

2022-01-30 04:56 UTC, miller-kevin requested changes

2022-01-30 04:56 UTC, miller-kevin commented on src/components/HelloWorld.vue
> +      <!-- <pre>
Clean up commented code

2022-01-30 04:56 UTC, miller-kevin commented on src/components/HelloWorld.vue
> +      <ssh-pre class="mb-4" language="html" copy-button @copied="onCopiedDoSomething" dark reactive>
This should be added to all of them

2022-01-30 04:56 UTC, miller-kevin commented on src/components/HelloWorld.vue
> +    onCopiedDoSomething() {
Needs a more appropriate name

2022-01-30 04:56 UTC, miller-kevin commented on src/components/AppHeader.vue
> +      <!-- <b-navbar-nav>
No leftover commented code

2022-01-30 04:56 UTC, miller-kevin commented on src/components/AppHeader.vue
> +          <!-- Place this tag where you want the button to render. -->
Remove tutorial comments

2022-01-30 04:56 UTC, miller-kevin commented on src/main.js
> +// Optionally install the BootstrapVue icon components plugin
Remove tutorial comments

2022-01-30 05:00 UTC, richardsaseun14 commented on src/components/HelloWorld.vue
> +    onCopiedDoSomething() {
onCopySuccess() should be fine?

2022-01-30 05:16 UTC, miller-kevin commented on src/components/HelloWorld.vue
> +    onCopiedDoSomething() {
onCopy would make more sense

2022-01-30 07:31 UTC, miller-kevin commented
@richardsaseun14 keep in mind that in addition to the PR comments, there's also a merge conflict on package-lock.json

2022-02-03 15:12 UTC, richardsaseun14 commented
i have resolved the merge conflict

2022-02-08 23:51 UTC, miller-kevin commented
@richardsaseun14 There are still pending comments, FYI

2022-03-01 23:10 UTC, richardsaseun14 commented
@miller-kevin I have sorted out all comments.

2022-03-02 03:21 UTC, miller-kevin commented
@richardsaseun14 There are several remaining comments

2022-03-02 11:54 UTC, richardsaseun14 commented
<img width="936" alt="image" src="https://user-images.githubusercontent.com/16512806/156356804-0adb7118-3e16-42a0-a2a9-70d5a8ef62e7.png">

Please where can I see those comment because the one available to me has been sorted. I added a screenshot to show all the comments on my end which I have resolved

2022-03-02 13:23 UTC, miller-kevin commented
@richardsaseun14 huh, that's super weird. I still see these two which aren't visible to you

![Screenshot_20220302-082236_Chrome](https://user-images.githubusercontent.com/50149901/156370013-92186bb1-20a3-45df-81df-d34aff8bcb9e.jpg)

2022-03-10 15:54 UTC, miller-kevin requested changes

2022-03-10 15:54 UTC, miller-kevin commented on src/components/HelloWorld.vue
> +      <ssh-pre class="mb-4" language="html" copy-button @copied="onCopySuccess" dark reactive>
onCopySuccess doesn't exist

2022-03-10 15:54 UTC, miller-kevin commented on src/components/HelloWorld.vue
> +      <ssh-pre class="mb-4" language="html" copy-button @copied="onCopySuccess" dark reactive>
These all share the same copy text, if you copy one, they'll all display "copy". Should be changed, cleanest way is probably breaking each of these copy and pasted sections into a component so they each have their own copy text

2022-03-11 00:12 UTC, richardsaseun14 commented
@miller-kevin i have resolved all pending comments

2022-03-11 00:21 UTC, miller-kevin approved these changes

2022-03-11 00:21 UTC, merged